const db_name = "mydb"
const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS'
const NEW_ATTACHEMENTS = 'NEW_ATTACHEMENTS'
const NEW_ATTACHEMENTS_ALERT = 'NEW_ATTACHEMENTS_ALERT'
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT'
const NEW_MESSAGE = "NEW_MESSAGE"
const NEW_REQUEST = "NEW_REQUEST"

export {
    db_name,
    ALERT,
    REFETCH_CHATS,
    NEW_ATTACHEMENTS,
    NEW_MESSAGE_ALERT,
    NEW_MESSAGE,
    NEW_REQUEST,
    NEW_ATTACHEMENTS_ALERT
}
